### ISSUE TITLE
Build failing on `namespace`

### ISSUE THREAD

**Issue by scoates** [anders0nmat/swift-esp-http#1]
Hi.

This looks like a really useful project; exactly what I was looking for for an Embedded Swift on ESP32 project.

Hope it's okay to ask for help here (also hope it's an issue that we can fix, but might just be something I'm doing wrong).

- I've cloned this project.
- I have a working ESP-IDF (I have it working for the example LED strip code). I've tried both 6-dev and 5.5.1.
- I'm on Swift 6.2 (via `swiftly`) on MacOS
- I can successfully `swiftly run idf.py set-target esp32c6`
- In this project when I `swiftly run idf.py build`, it complains about `namespace` in `esp_htto_includes.h`:

 ```
(more; redacted)
Building for production...
[10/13] Compiling HttpServer Http.swift
<module-includes>:1:10: note: in file included from <module-includes>:1:
1 | #include "/Users/sean/src/swift-esp-http/main/.build/checkouts/EspSwift/Source/CHttpServer/include/esp_http_includes.h"
  |          `- note: in file included from <module-includes>:1:
2 |

/Users/sean/src/swift-esp-http/main/.build/checkouts/EspSwift/Source/CHttpServer/include/esp_http_includes.h:14:1: error: unknown type name 'namespace'
12 | }
13 |
14 | namespace httpd_shims {
   | `- error: unknown type name 'namespace'
15 |    const esp_err_t _ESP_ERR_HTTPD_ALLOC_MEM = ESP_ERR_HTTPD_ALLOC_MEM;
16 |    const esp_err_t _ESP_ERR_HTTPD_TASK = ESP_ERR_HTTPD_TASK;
(more; redacted)
```

Any ideas where to look next? I'm pretty bad at this C/C++ build system stuff, and was hoping to get there quicker with the help of your project.

Thanks!

S

**Comment by scoates** [comment]
FWIW, I also tried this on the following config (I saw you used 5.2.2 in [swift-embedded-pm](https://github.com/anders0nmat/swift-embedded-pm)), and observed the same (or very similar) behaviour.

```
❯ swiftly run idf.py --version
ESP-IDF v5.2.2
❯ swiftly run swift --version
Apple Swift version 6.0.3 (swift-6.0.3-RELEASE)
Target: arm64-apple-macosx16.0
```

**Comment by anders0nmat** [comment]
This sounds awfully similar to some issues i've had in the past. If only i could remember how i fixed it :/

**Comment by anders0nmat** [comment]
Ah, yeah. i never updated the repo it seems. It seems i was unable to directly fix the `unknown type name "namespace"` issue, therefore i circumvented it.

The namespace was only a fancy way to group the constants anyway, so just defining the constants directly should work just fine:

```c
/*
namespace httpd_shims {
	const esp_err_t _ESP_ERR_HTTPD_ALLOC_MEM = ESP_ERR_HTTPD_ALLOC_MEM;
	const esp_err_t _ESP_ERR_HTTPD_TASK = ESP_ERR_HTTPD_TASK;
	const esp_err_t _ESP_ERR_HTTPD_HANDLERS_FULL = ESP_ERR_HTTPD_HANDLERS_FULL;
	const esp_err_t _ESP_ERR_HTTPD_HANDLER_EXISTS = ESP_ERR_HTTPD_HANDLER_EXISTS;
}
*/

// Instead of ^^^ use vvv

const esp_err_t _ESP_ERR_HTTPD_ALLOC_MEM = ESP_ERR_HTTPD_ALLOC_MEM;
const esp_err_t _ESP_ERR_HTTPD_TASK = ESP_ERR_HTTPD_TASK;
const esp_err_t _ESP_ERR_HTTPD_HANDLERS_FULL = ESP_ERR_HTTPD_HANDLERS_FULL;
const esp_err_t _ESP_ERR_HTTPD_HANDLER_EXISTS = ESP_ERR_HTTPD_HANDLER_EXISTS;
```

I am not sure if this is the only thing necessary, but it should get you further. Also i should really commit my changes, considering it is wayy more complete and actually compiles 😅

**Comment by scoates** [comment]
Thanks! I had it partially working by removing these shims (and their references in the code) and ran into another build problem. But I'll give this a shot and see if I can get further (might be an IDF/Swift versioning problem with the other build issue in cmake).

**Comment by scoates** [comment]
I provided a PR based on your suggestion, [here](https://github.com/anders0nmat/EspSwift/pull/1). (feel absolutely free to make whatever changes on own; just providing a PR for ease of merge).

This resolved my *build* issue, but I still have another issue with cmake; I'll open a second issue.

Thanks again!
